#!/command/with-contenv bash
# shellcheck shell=bash

PUID=${PUID:-911}
PGID=${PGID:-911}

groupmod -o -g "${PGID}" abc
usermod -o -u "${PUID}" abc

cat <<'EOF'
--------------------------------------------
    _          _   _ _      __  __    _____
   / \   _ __ | |_(_) | __ _\ \/ /   |___ /
  / _ \ | `_ \| __| | |/ _` |\  /_____ |_ \
 / ___ \| | | | |_| | | (_| |/  \_____|__) |
/_/   \_\_| |_|\__|_|_|\__,_/_/\_\   |____/

--------------------------------------------
GID/UID
--------------------------------------------
EOF
cat <<EOF

User uid:    $(id -u abc)
User gid:    $(id -g abc)
--------------------------------------------

EOF

chown -R abc:abc /app
chown -R abc:abc /config
chown -R abc:abc /defaults
